# permissions to do viewer mykinds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mykind-viewer-role
rules:
- apiGroups:
  - webapp.h3poteto.dev
  resources:
  - mykinds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapp.h3poteto.dev
  resources:
  - mykinds/status
  verbs:
  - get
